name: Tech Thumbs
favicon: null
layout_spectrum: 0.6559583784546703
typography_spectrum: 0.9249381409026682
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.9225147133693099
  lightness: 0.5251002141740173
  saturation: 0.016267968574538827
  rhythmicContrast: 0.23325764597393572
purpose: []
